[package]
name = "havregryn"
version = "0.1.0"
edition = "2021"
authors = ["Viktor Sandström <sandstrom.viktor@gmail.com>"]
license = "GPL-3.0-or-later"
homepage = "https://youtu.be/dQw4w9WgXcQ"
description = "Granular sampler"

[workspace]
members = ["xtask"]

[lib]
crate-type = ["cdylib"]

[dependencies]
# Remove the `assert_process_allocs` feature to allow allocations on the audio
# thread in debug builds.
# nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = ["assert_process_allocs", "standalone"] }
nih_plug = { path = "../nih-plug", features = ["assert_process_allocs", "standalone"] }
# nih_plug_webview = { path = "../nih-plug-webview" }
# nih_plug_iced = { path = "../nih-plug/nih_plug_iced" }
# nih_plug_egui = { path = "../nih-plug/nih_plug_egui" }
nih_plug_vizia = { path = "../nih-plug/nih_plug_vizia" }
atomic_float = "0.1"

dsp = { path = "../dsp/dsp"}
grains = { path = "../dsp/grains" }
wavetable = { path = "../dsp/wavetable"}
waveshape = { path = "../dsp/waveshape"}
trig = { path = "../dsp/trig"}
interpolation = { path = "../dsp/interpolation"}
envelope = { path = "../dsp/envelope"}
rand = "0.8.5"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0"
# Uncomment the below line to disable the on-by-default VST3 feature to remove
# the GPL compatibility requirement
# nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", default-features = false, features = ["assert_process_allocs"] }

[profile.release]
lto = "thin"
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"




