[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
nih_plug_xtask = { git = "https://github.com/robbert-vdh/nih-plug.git" }

# [target.x86_64-pc-windows-gnu]
# linker = "x86_64-w64-mingw32-gcc"
