name: compile Havregryn
run-name: build ${{github.repositoryUrl}}
on: 
  push:
    tags:
      - v*
jobs:
  compile_job:
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    env: 
      CMD: cargo xtask bundle havregryn --release
      TARGET: target/bundled/Havregryn.vst3
      DEST: Havregryn.vst3
      TOOLCHAINS: x86_64-apple-darwin aarch64-apple-darwin x86_64-pc-windows-gnu

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      
      - name: install windows linker
        run: | 
          brew install mingw-w64

      - name: install rust toolchains
        run: | 
          for tc in ${TOOLCHAINS[@]}; do
            rustup target add $tc
          done

      - name: compile intel mac and zip
        run: |
          $CMD --target=x86_64-apple-darwin
          mv $TARGET ./$DEST
          zip -r Havregryn_macOS_intel.vst3.zip $DEST
          rm -r $DEST

      - name: compile arm mac and zip
        run: |
          $CMD --target=aarch64-apple-darwin
          mv $TARGET ./$DEST
          zip -r Havregryn_macOS_arm.vst3.zip $DEST
          rm -r $DEST
      
      - name: compile windows and zip
        run: | 
          $CMD --target=x86_64-pc-windows-gnu
          mv $TARGET ./$DEST
          zip -r Havregryn_Win.vst3.zip $DEST
          rm -r $DEST

      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'Havregryn_macOS_intel.vst3.zip, Havregryn_macOS_arm.vst3.zip, Havregryn_Win.vst3.zip' 
